name: Deploy Vite + TypeScript App + Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- Frontend: Static Web App ---
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Static Web App token
        id: get_token
        run: |
          APP_NAME="static-wapp-taskGen"
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          DEPLOY_TOKEN=$(az staticwebapp secrets list \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --query "properties.apiKey" -o tsv)
          echo "deploy_token=$DEPLOY_TOKEN" >> $GITHUB_OUTPUT

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_token.outputs.deploy_token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"

  # --- Backend: Function App 1 ---
  deploy_function1:
    runs-on: ubuntu-latest
    needs: build_and_deploy_frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy CRUD Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "func-crud-taskGen"
          package: "./api/api-function1"   # Points to the correct folder
          scm-do-build-during-deployment: true

  # --- Backend: Function App 2 ---
  deploy_function2:
    runs-on: ubuntu-latest
    needs: build_and_deploy_frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Login Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "func-login-taskGen"
          package: "./api/api-function2"   # Correct folder
          scm-do-build-during-deployment: true
