name: Deploy Monolithic Vite + Node Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Prepare Deployment Package
        run: |
          rm -rf deploy
          mkdir deploy
          cp -r frontend/dist/* deploy/
          cp -r endpoints/* deploy/
          rm -rf deploy/node_modules
          cd deploy
          npm ci --production

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure startup command
        run: |
          az webapp config set \
            --name app-service-taskGen-dev \
            --resource-group rg-taskGen-dev-weu \
            --startup-file "npm start"

      # 7️⃣ Get publish profile XML from Azure
      - name: Get Publish Profile
        id: get_profile
        run: |
          APP_NAME="app-service-taskGen-dev"
          az webapp deployment list-publishing-profiles \
            --name $APP_NAME \
            --resource-group rg-taskGen-dev-weu \
            --xml > publishProfile.xml
          echo "publishProfilePath=publishProfile.xml" >> $GITHUB_OUTPUT

      # 8️⃣ Deploy to Azure App Service using fetched profile
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app-service-taskGen-dev"
          publish-profile: ${{ steps.get_profile.outputs.publishProfilePath }}
          package: ./deploy
