name: Deploy Monolithic Vite + Node Backend (Dynamic)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 22
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # 4️⃣ Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # 5️⃣ Prepare deployment package
      - name: Prepare Deployment Package
        run: |
          rm -rf deploy
          mkdir deploy
          # Copy frontend build output
          cp -r frontend/dist/* deploy/
          # Copy backend code (your API folders inside endpoints)
          cp -r endpoints/* deploy/
          # Install production dependencies
          cd deploy
          npm ci --omit=dev
          cd ..

      # 6️⃣ Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7️⃣ Deploy to Azure dynamically (no publish profile)
      - name: Deploy to Azure App Service
        run: |
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          APP_NAME="app-service-taskGen-dev"

          echo "🔹 Zipping deployment package..."
          zip -r deploy.zip deploy

          echo "🚀 Deploying to Azure App Service..."
          az webapp deploy \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --src-path deploy.zip \
            --type zip

      # 8️⃣ (Optional) Verify deployment status
      - name: Verify Deployment
        run: |
          APP_NAME="app-service-taskGen-dev"
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          echo "🔍 Checking deployment logs..."
          az webapp log tail --name $APP_NAME --resource-group $RESOURCE_GROUP --timeout 10
