name: Deploy Monolithic Vite + Node Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # 4️⃣ Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # 5️⃣ Prepare deployment package
      - name: Prepare Deployment Package
        run: |
          rm -rf deploy
          mkdir deploy
          # Copy frontend build
          cp -r frontend/dist/* deploy/
          # Copy backend code
          cp -r endpoints/* deploy/
          # Copy root server.js
          cp server.js deploy/
          # Remove dev dependencies if any
          rm -rf deploy/node_modules
          cd deploy
          # Initialize minimal package.json if not present
          npm init -y
          # Install runtime dependencies
          npm install express

      # 6️⃣ Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7️⃣ Deploy to Azure App Service using zip deployment
      - name: Deploy to Azure App Service
        run: |
          APP_NAME="app-service-taskGen-dev"
          RESOURCE_GROUP="rg-taskGen-dev-weu"

          # Zip deployment package
          zip -r deploy.zip .

          # Deploy to Azure
          az webapp deployment source config-zip \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --src deploy.zip

      # 8️⃣ Set startup command for Node.js
      - name: Configure Startup Command
        run: |
          APP_NAME="app-service-taskGen-dev"
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          az webapp config set \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --startup-file "node server.js"

      # 9️⃣ Restart App Service
      - name: Restart App Service
        run: |
          APP_NAME="app-service-taskGen-dev"
          RESOURCE_GROUP="rg-taskGen-dev-weu"
          az webapp restart \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME
