name: Deploy Vite + TypeScript App to Azure Static Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Get deployment token dynamically
      - name: Get Azure Static Web Apps Deployment Token
        id: get_token
        run: |
          APP_NAME="static-wapp-taskGen"           # Update with your Bicep-created app name
          RESOURCE_GROUP="rg-taskGen-dev-weu" # Update with your Bicep-created resource group

          DEPLOY_TOKEN=$(az staticwebapp secrets list \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --query "properties.apiKey" -o tsv)

          echo "deploy_token=$DEPLOY_TOKEN" >> $GITHUB_OUTPUT

      # 7️⃣ Deploy to Azure
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_token.outputs.deploy_token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"       # your app source root
          output_location: "dist" # Vite build output
