name: Deploy Monolithic Vite + TypeScript App + APIs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_app:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js (Vite requires 20.19+ or >=22.12)
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Build Frontend
      - name: Install & Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # 4️⃣ Build Backend
      - name: Install & Build Backend
        run: |
          cd endpoints
          npm ci
          npm run build || echo "No build script, skipping"

      # 5️⃣ Prepare deployment package
      - name: Prepare deployment package
        run: |
          rm -rf deploy
          mkdir deploy
          # Copy frontend build
          cp -r frontend/dist/* deploy/
          # Copy backend compiled code
          cp -r endpoints/* deploy/
          # Remove dev dependencies if any
          rm -rf deploy/node_modules
          cd deploy
          npm ci --production

      # 6️⃣ Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7️⃣ Deploy to App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app-service-taskGen-dev"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy
