name: Build and deploy dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '~20'

      # 3️⃣ Unzip node_modules
      - name: Unzip node_modules
        run: unzip node_modules.zip -d .

      # 4️⃣ Build frontend (inside ./frontend)
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      # 5️⃣ Confirm build output
      - name: Check dist folder
        run: ls -la frontend/dist

      # 6️⃣ Package everything (server + built frontend + node_modules)
      - name: Package app for deployment
        run: zip -r monolith-app.zip . -x '*.git*' > /dev/null

      # 7️⃣ Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: monolith-app
          path: monolith-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1️⃣ Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monolith-app

      # 2️⃣ Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Deploy directly to Azure App Service
      - name: Deploy to Azure Web App
        run: |
          set +e
          az webapp deploy \
            --name app-service-taskGen-dev \
            --resource-group rg-taskGen-dev-weu \
            --src-path monolith-app.zip \
            --type zip
          set -e
          # Verify deployment succeeded
          az webapp show \
            --name app-service-taskGen-dev \
            --resource-group rg-taskGen-dev-weu \
            --query "state"
