name: Build and deploy monolithic Node.js app to Azure Web App - app-service-taskGen-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '~20'

      # 3️⃣ Install backend deps
      - name: Install root dependencies
        run: npm install

      # 4️⃣ Build frontend (inside ./frontend)
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      # 5️⃣ Confirm build output
      - name: Check dist folder
        run: ls -la frontend/dist

      # 6️⃣ Package everything (server + built frontend)
      - name: Package app for deployment
        run: zip -r monolith-app.zip . -x '*.git*' > /dev/null

      # 7️⃣ Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: monolith-app
          path: monolith-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1️⃣ Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: monolith-app

      # 2️⃣ Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Deploy directly to Azure App Service
      - name: Deploy to Azure Web App
        run: |
          echo "🚀 Starting deployment to Azure App Service..."
          set +e
          DEPLOY_OUTPUT=$(az webapp deploy \
            --name app-service-taskGen-dev \
            --resource-group rg-taskGen-dev-weu \
            --src-path monolith-app.zip \
            --type zip 2>&1)
          DEPLOY_EXIT_CODE=$?
          set -e

          echo "$DEPLOY_OUTPUT"

          if echo "$DEPLOY_OUTPUT" | grep -q "504"; then
            echo "⚠️  Received 504 Gateway Timeout — checking if deployment actually succeeded..."
          elif [ $DEPLOY_EXIT_CODE -ne 0 ]; then
            echo "❌ Deployment command failed (exit code $DEPLOY_EXIT_CODE)."
            exit 1
          fi

          echo "⏳ Polling Kudu for deployment status..."
          ATTEMPTS=0
          MAX_ATTEMPTS=20
          STATUS=""

          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            STATUS=$(az rest \
              --method get \
              --uri "https://app-service-taskgen-dev.scm.azurewebsites.net/api/deployments/latest" \
              --query "status" -o tsv 2>/dev/null || echo "unknown")

            echo "🔍 Attempt $((ATTEMPTS+1)) - Latest Kudu deployment status: ${STATUS}"

            if [ "$STATUS" = "4" ]; then
              echo "✅ Deployment completed successfully!"
              exit 0
            elif [ "$STATUS" = "3" ]; then
              echo "❌ Deployment failed in Kudu!"
              exit 1
            fi

            ATTEMPTS=$((ATTEMPTS+1))
            sleep 15
          done

          echo "⚠️  Deployment still running or unknown after $((MAX_ATTEMPTS*15)) seconds. Please check Kudu manually."
          exit 1





